site_name: My Docs
site_url: https://reg1z.github.io
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
