repo_url: https://github.com/reg1z/reg1z.github.io
repo_name: reg1z/reg1z.github.io

site_name: reg1z
site_url: https://reg1z.github.io
site_description: Parsing Logs since 2005
site_author: reg1z

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys

theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
   # - navigation.prune
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share

  font:
    text: Inter
    #text: Syne Mono

  icon:
    repo: fontawesome/brands/github

  logo: assets/logo.png
  favicon: assets/logo.png

  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

plugins:
  - blog:
      blog_dir: .
      post_dir: posts
  - search:
      enabled: true
  - callouts
  - social:
      cards_layout: default
      cards_layout_options:
        background_color: "#00000000"
        background_image: layouts/whitehat1.png
        logo: layouts/logo2.png
        font_family: Inter
  - tags
  - optimize:
      cache: false
  #- privacy
  - awesome-nav

#nav:
#  - Home: blog/index.md
