repo_url: https://github.com/reg1z/reg1z.github.io
repo_name: reg1z/reg1z.github.io

site_name: Parser of Logs
site_url: https://reg1z.github.io
site_description: Parser of Logs
site_author: reg1z

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys

plugins:
  - blog
  - callouts
  - search:
      enabled: true
  - group:
      enabled: !ENV CI
      plugins:
        - social:
            cards_layout_options:
              #background_color: transparent
              background_image: assets/images/social/whitehat.webp
              font_family: Inter
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize
        - privacy

extra_css:
  - stylesheets/extra.css

theme:
  font:
    text: Inter
    #text: Syne Mono

  logo: assets/logo.png
  favicon: assets/logo.png

  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

