site_name: My Docs

site_url: https://reg1z.github.io

site_description: Parser of Logs

site_author: reg1z

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - blog
  - search:
      enabled: true
  - callouts
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: null
        background_image: assets/images/social/whitehat.webp
        font_family: Inter

extra_css:
  - stylesheets/extra.css

theme:
  font:
    text: Inter
    #text: Syne Mono

  logo: assets/logo.png
  favicon: assets/logo.png

  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

