repo_url: https://github.com/reg1z/reg1z.github.io
repo_name: reg1z/reg1z.github.io

site_name: Parser of Logs
site_url: https://reg1z.github.io
site_description: Parser of Logs
site_author: reg1z

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys

theme:
  font:
    text: Inter
    #text: Syne Mono

  logo: assets/logo.png
  favicon: assets/logo.png

  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

plugins:
  - blog
  - callouts
  - search:
      enabled: true
  - social:
      cards_layout: default
      cards_layout_options:
        logo: layouts/logo2.png
        background_color: "#00000000"
        background_image: layouts/whitehat0.png
        font_family: Inter
        description: " "
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimize
        - privacy


